apiVersion: batch/v1
kind: Job
metadata:
  name: insert-pod-job
spec:
  template:
    metadata:
      labels:
        app: insert-pod-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: runner
        image: zacharybloss/python-psycopg2
        command: ["/bin/bash", "-c", "python /opt/script/script.py"]
        volumeMounts:
          - name: script-vol
            mountPath: /opt/script
        env:
          - name: DB_HOST
            value: "postgresql-db"
          - name: DB_NAME
            value: "testdb"
          - name: DB_USER
            value: "postgres"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: script-vol
        configMap:
          name: script-config
