apiVersion: v1
kind: ConfigMap
metadata:
  name: script-config
data:
  script.py: |
    import os
    import psycopg2

    db_host = os.getenv('DB_HOST')
    db_name = os.getenv('DB_NAME')
    db_user = os.getenv('DB_USER')
    db_password = os.getenv('DB_PASSWORD')
    pod_name = os.getenv('POD_NAME')

    try:
        conn = psycopg2.connect(
            host=db_host,
            dbname=db_name,
            user=db_user,
            password=db_password
        )
        cursor = conn.cursor()
        cursor.execute("CREATE TABLE IF NOT EXISTS pods (name TEXT);")
        cursor.execute("INSERT INTO pods (name) VALUES (%s);", (pod_name,))
        conn.commit()
        cursor.close()
        conn.close()
        print(f"Inserted pod name {pod_name} into database.")
    except Exception as e:
        print(f"Database operation failed: {e}")
